CREATE TABLE animais (
    cga INT AUTO_INCREMENT PRIMARY KEY,
    serie CHAR(4) NOT NULL,
    rgn CHAR(16) NOT NULL,
    sexo INT NOT NULL,
    nome VARCHAR(24) NOT NULL,
    dt_nasc DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);